import { PromptDecorator as Prompt, Injectable, ExecutionContext } from '@nitrostack/core';

type PromptArgumentValue = string | number | boolean | undefined;
type PromptMessage = { role: 'user' | 'assistant' | 'system'; content: string };
@Injectable({ deps: [] })
export class InsuranceReferencePrompts {
  @Prompt({
    name: 'explain-red-flag',
    description: 'Explains a policy red flag in plain language for a first-time insurance buyer',
    arguments: [
      { name: 'clauseText', description: 'The original policy wording', required: true },
      { name: 'plainLanguage', description: 'The short plain-language explanation already generated by analyze_policy', required: true },
      { name: 'severity', description: 'How serious this red flag is (high, medium, low)', required: false },
    ],
  })
  async explainRedFlag(
    args: Record<string, PromptArgumentValue>,
    ctx: ExecutionContext,
  ): Promise<PromptMessage[]> {
    ctx.logger.info('Building explain-red-flag prompt');
    return [
      {
        role: 'system',
        content:
          'You are explaining an insurance policy red flag to someone buying insurance for the first time. ' +
          'Be concrete about what it means for their money, avoid jargon, and suggest one practical next step.',
      },
      {
        role: 'user',
        content:
          `Original policy clause: "${args.clauseText}"\n` +
          `Quick explanation: "${args.plainLanguage}"\n` +
          `Severity: ${args.severity ?? 'unspecified'}\n\n` +
          `Explain this clearly to a first-time insurance buyer, in 2-3 sentences.`,
      },
    ];
  }
}